# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: kick.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='kick.proto',
  package='kick',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\nkick.proto\x12\x04kick\"!\n\x0bKickRequest\x12\x12\n\nkickerName\x18\x01 \x01(\t\"#\n\tKickReply\x12\x16\n\x0eregistrationId\x18\x01 \x01(\t2:\n\nKickServer\x12,\n\x04Kick\x12\x11.kick.KickRequest\x1a\x0f.kick.KickReply\"\x00\x62\x06proto3'
)




_KICKREQUEST = _descriptor.Descriptor(
  name='KickRequest',
  full_name='kick.KickRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='kickerName', full_name='kick.KickRequest.kickerName', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=20,
  serialized_end=53,
)


_KICKREPLY = _descriptor.Descriptor(
  name='KickReply',
  full_name='kick.KickReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='registrationId', full_name='kick.KickReply.registrationId', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=55,
  serialized_end=90,
)

DESCRIPTOR.message_types_by_name['KickRequest'] = _KICKREQUEST
DESCRIPTOR.message_types_by_name['KickReply'] = _KICKREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

KickRequest = _reflection.GeneratedProtocolMessageType('KickRequest', (_message.Message,), {
  'DESCRIPTOR' : _KICKREQUEST,
  '__module__' : 'kick_pb2'
  # @@protoc_insertion_point(class_scope:kick.KickRequest)
  })
_sym_db.RegisterMessage(KickRequest)

KickReply = _reflection.GeneratedProtocolMessageType('KickReply', (_message.Message,), {
  'DESCRIPTOR' : _KICKREPLY,
  '__module__' : 'kick_pb2'
  # @@protoc_insertion_point(class_scope:kick.KickReply)
  })
_sym_db.RegisterMessage(KickReply)



_KICKSERVER = _descriptor.ServiceDescriptor(
  name='KickServer',
  full_name='kick.KickServer',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=92,
  serialized_end=150,
  methods=[
  _descriptor.MethodDescriptor(
    name='Kick',
    full_name='kick.KickServer.Kick',
    index=0,
    containing_service=None,
    input_type=_KICKREQUEST,
    output_type=_KICKREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_KICKSERVER)

DESCRIPTOR.services_by_name['KickServer'] = _KICKSERVER

# @@protoc_insertion_point(module_scope)
