# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import kick_pb2 as kick__pb2


class KickServerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Kick = channel.unary_unary(
                '/kick.KickServer/Kick',
                request_serializer=kick__pb2.KickRequest.SerializeToString,
                response_deserializer=kick__pb2.KickReply.FromString,
                )


class KickServerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Kick(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_KickServerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Kick': grpc.unary_unary_rpc_method_handler(
                    servicer.Kick,
                    request_deserializer=kick__pb2.KickRequest.FromString,
                    response_serializer=kick__pb2.KickReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'kick.KickServer', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class KickServer(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Kick(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/kick.KickServer/Kick',
            kick__pb2.KickRequest.SerializeToString,
            kick__pb2.KickReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
